package com.expatportal.core.soap.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.7
 * 2019-07-21T22:35:47.305-05:00
 * Generated source version: 2.5.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PCH_MAWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface PCHMAWebServiceSoap {

    @WebMethod(operationName = "UploadFile", action = "http://tempuri.org/UploadFile")
    @RequestWrapper(localName = "UploadFile", targetNamespace = "http://tempuri.org/", className = "com.expatportal.soap.wsdl.UploadFile")
    @ResponseWrapper(localName = "UploadFileResponse", targetNamespace = "http://tempuri.org/", className = "com.expatportal.soap.wsdl.UploadFileResponse")
    @WebResult(name = "UploadFileResult", targetNamespace = "http://tempuri.org/")
    public com.expatportal.core.soap.wsdl.OutputResult uploadFile(
        @WebParam(name = "UID", targetNamespace = "http://tempuri.org/")
        java.lang.String uid,
        @WebParam(name = "PassCode", targetNamespace = "http://tempuri.org/")
        java.lang.String passCode,
        @WebParam(name = "fsXml", targetNamespace = "http://tempuri.org/")
        byte[] fsXml,
        @WebParam(name = "fsImage", targetNamespace = "http://tempuri.org/")
        byte[] fsImage,
        @WebParam(name = "ImagefileName", targetNamespace = "http://tempuri.org/")
        java.lang.String imagefileName
    );
}
