
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.expatportal.core.soap.wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.7
 * 2019-07-21T22:35:47.288-05:00
 * Generated source version: 2.5.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "PCH_MAWebService",
                      portName = "PCH_MAWebServiceHttpGet",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "https://www.hovs-pch.com/PCHMA_SSP/PCH_MAWebService.asmx?wsdl",
                      endpointInterface = "com.expatportal.soap.wsdl.PCHMAWebServiceHttpGet")
                      
public class PCHMAWebServiceHttpGetImpl implements PCHMAWebServiceHttpGet {

    private static final Logger LOG = Logger.getLogger(PCHMAWebServiceHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see com.expatportal.soap.wsdl.PCHMAWebServiceHttpGet#uploadFile(java.lang.String  uid ,)java.lang.String  passCode ,)com.expatportal.soap.wsdl.StringArray  fsXml ,)com.expatportal.soap.wsdl.StringArray  fsImage ,)java.lang.String  imagefileName )*
     */
    public com.expatportal.core.soap.wsdl.OutputResult uploadFile(java.lang.String uid,java.lang.String passCode,StringArray fsXml,StringArray fsImage,java.lang.String imagefileName) { 
        LOG.info("Executing operation uploadFile");
        System.out.println(uid);
        System.out.println(passCode);
        System.out.println(fsXml);
        System.out.println(fsImage);
        System.out.println(imagefileName);
        try {
            com.expatportal.core.soap.wsdl.OutputResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
