package com.expatportal.core.soap.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.7
 * 2019-07-21T22:35:47.358-05:00
 * Generated source version: 2.5.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "PCH_MAWebServiceHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PCHMAWebServiceHttpGet {

    @WebMethod(operationName = "UploadFile")
    @WebResult(name = "OutputResult", targetNamespace = "http://tempuri.org/", partName = "Body")
    public OutputResult uploadFile(
        @WebParam(partName = "UID", name = "UID", targetNamespace = "http://tempuri.org/")
        java.lang.String uid,
        @WebParam(partName = "PassCode", name = "PassCode", targetNamespace = "http://tempuri.org/")
        java.lang.String passCode,
        @WebParam(partName = "fsXml", name = "fsXml", targetNamespace = "http://tempuri.org/")
        StringArray fsXml,
        @WebParam(partName = "fsImage", name = "fsImage", targetNamespace = "http://tempuri.org/")
        StringArray fsImage,
        @WebParam(partName = "ImagefileName", name = "ImagefileName", targetNamespace = "http://tempuri.org/")
        java.lang.String imagefileName
    );
}
