
package com.expatportal.core.soap.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.7
 * 2019-07-21T22:35:47.161-05:00
 * Generated source version: 2.5.7
 * 
 */
public final class PCHMAWebServiceHttpGet_PCHMAWebServiceHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "PCH_MAWebService");

    private PCHMAWebServiceHttpGet_PCHMAWebServiceHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PCHMAWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PCHMAWebService ss = new PCHMAWebService(wsdlURL, SERVICE_NAME);
        PCHMAWebServiceHttpGet port = ss.getPCHMAWebServiceHttpGet();  
        
        {
        System.out.println("Invoking uploadFile...");
        java.lang.String _uploadFile_uid = "";
        java.lang.String _uploadFile_passCode = "";
        com.expatportal.core.soap.wsdl.StringArray _uploadFile_fsXml = null;
        com.expatportal.core.soap.wsdl.StringArray _uploadFile_fsImage = null;
        java.lang.String _uploadFile_imagefileName = "";
        com.expatportal.core.soap.wsdl.OutputResult _uploadFile__return = port.uploadFile(_uploadFile_uid, _uploadFile_passCode, _uploadFile_fsXml, _uploadFile_fsImage, _uploadFile_imagefileName);
        System.out.println("uploadFile.result=" + _uploadFile__return);


        }

        System.exit(0);
    }

}
